=== viticm/pap2/Source/Tools/biztool/src/Share/Header/FSEye/fseye_protocol.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ProtocolDefination">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Protocol" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ProtocolName">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="3"/>
										<xs:maxLength value="40"/>
										<xs:pattern value="([_0-9a-zA-Z])*"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Portable" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
							<xs:element name="HasHeader" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
							<xs:element name="ProtocolField" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="FieldName">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="40"/>
													<xs:pattern value="([_0-9a-zA-Z])*"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="FieldType">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="TypeName">
														<xs:simpleType>
															<xs:restriction base="xs:string"/>
														</xs:simpleType>
													</xs:element>
													<xs:element name="TypeLength" minOccurs="0" maxOccurs="unbounded">
														<xs:simpleType>
															<xs:restriction base="xs:integer"/>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ErrorCode" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="3"/>
										<xs:maxLength value="40"/>
										<xs:pattern value="([_0-9a-zA-Z])*"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Description">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="100"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== viticm/pap2/Source/Tools/biztool/src/Share/Header/FSEye/fseye_protocol.xml
<?xml version="1.0" encoding="UTF-8"?>
<ProtocolDefination xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fseye_protocol.xsd">
	<!--协议代码段-->
	<!--PING-->
	<Protocol>
		<ProtocolName>g2e_ping</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--PING返回-->
	<Protocol>
		<ProtocolName>e2g_ping</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--打开文件-->
	<Protocol>
		<ProtocolName>e2g_openfile</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>bFlag</FieldName>
			<FieldType>
				<TypeName>byte</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>bFullPath</FieldName>
			<FieldType>
				<TypeName>byte</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>szFileName</FieldName>
			<FieldType>
				<TypeName>string</TypeName>
				<TypeLength>256</TypeLength>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--打开文件返回-->
	<Protocol>
		<ProtocolName>g2e_openfile</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nFileLen</FieldName>
			<FieldType>
				<TypeName>uint</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nRetCode</FieldName>
			<FieldType>
				<TypeName>int</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--读文件-->
	<Protocol>
		<ProtocolName>e2g_readfile</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nDataLen</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--读文件返回-->
	<Protocol>
		<ProtocolName>g2e_readfile</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nReadLen</FieldName>
			<FieldType>
				<TypeName>uint</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>szBuf</FieldName>
			<FieldType>
				<TypeName>byte</TypeName>
				<TypeLength>4096</TypeLength>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nRetCode</FieldName>
			<FieldType>
				<TypeName>int</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--写文件-->
	<Protocol>
		<ProtocolName>e2g_writefile</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nDataLen</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>szBuf</FieldName>
			<FieldType>
				<TypeName>byte</TypeName>
				<TypeLength>4096</TypeLength>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--写文件返回-->
	<Protocol>
		<ProtocolName>g2e_writefile</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nWritedLen</FieldName>
			<FieldType>
				<TypeName>uint</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nRetCode</FieldName>
			<FieldType>
				<TypeName>int</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--移动到文件某个位置-->
	<Protocol>
		<ProtocolName>e2g_seekfile</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>bKeep</FieldName>
			<FieldType>
				<TypeName>byte</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nOffset</FieldName>
			<FieldType>
				<TypeName>uint</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--移动到文件某个位置返回-->
	<Protocol>
		<ProtocolName>g2e_seekfile</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nRetCode</FieldName>
			<FieldType>
				<TypeName>int</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--关闭文件-->
	<Protocol>
		<ProtocolName>e2g_closefile</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--关闭文件返回-->
	<Protocol>
		<ProtocolName>g2e_closefile</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nRetCode</FieldName>
			<FieldType>
				<TypeName>int</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--装载插件-->
	<Protocol>
		<ProtocolName>e2g_loadplug</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--装载插件返回-->
	<Protocol>
		<ProtocolName>g2e_loadplug</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nRetCode</FieldName>
			<FieldType>
				<TypeName>int</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--卸载插件-->
	<Protocol>
		<ProtocolName>e2g_unloadplug</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--卸载插件返回-->
	<Protocol>
		<ProtocolName>g2e_unloadplug</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nRetCode</FieldName>
			<FieldType>
				<TypeName>int</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--得到CPU基本信息-->
	<Protocol>
		<ProtocolName>e2g_getcpubaseinfo</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--CPU基本信息-->
	<Protocol>
		<ProtocolName>cpubaseinfo</ProtocolName>
		<Portable>false</Portable>
		<ProtocolField>
			<FieldName>szCPUName</FieldName>
			<FieldType>
				<TypeName>string</TypeName>
				<TypeLength>100</TypeLength>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>szCPUVendor</FieldName>
			<FieldType>
				<TypeName>string</TypeName>
				<TypeLength>100</TypeLength>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>szCPUDesc</FieldName>
			<FieldType>
				<TypeName>string</TypeName>
				<TypeLength>100</TypeLength>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nCPULoad</FieldName>
			<FieldType>
				<TypeName>int</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--得到CPU基本信息返回-->
	<Protocol>
		<ProtocolName>g2e_getcpubaseinfo</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nCPUCount</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>Processor</FieldName>
			<FieldType>
				<TypeName>cpubaseinfo</TypeName>
				<TypeLength>10</TypeLength>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--得到CPU负载-->
	<Protocol>
		<ProtocolName>e2g_getcpuload</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--得到CPU负载返回-->
	<Protocol>
		<ProtocolName>g2e_getcpuload</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nCPUCount</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nLoad</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
				<TypeLength>10</TypeLength>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--得到磁盘信息-->
	<Protocol>
		<ProtocolName>e2g_getmeminfo</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--得到内存信息返回-->
	<Protocol>
		<ProtocolName>g2e_getmeminfo</ProtocolName>
		<Portable>true</Portable>
		<ProtocolField>
			<FieldName>Protocol</FieldName>
			<FieldType>
				<TypeName>uint16</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nTotalMem</FieldName>
			<FieldType>
				<TypeName>uint</TypeName>
			</FieldType>
		</ProtocolField>
		<ProtocolField>
			<FieldName>nFreeMem</FieldName>
			<FieldType>
				<TypeName>uint</TypeName>
			</FieldType>
		</ProtocolField>
	</Protocol>
	<!--得到磁盘信息-->
	<Protocol>
		<ProtocolName>e2g_getdiskinfo</ProtocolName>
		<Portable>true</Portable>
